name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate PHP files
        run: |
          find plugins -name "*.php" -print0 | xargs -0 -n1 php -l
